### ISSUE TITLE
PS Audio DirectStream DAC 

### ISSUE THREAD

**Issue by norrest** [lintweaker/xmos-native-dsd#17]
Hello! There is an idea to check the Native mode with this DAC. But unfortunately it locally, I can not do that. I can only prepare  OS system in advance and send the person to be tested.
Maybe someone will tell USB_ID?
Maybe some like USB_ID(**0x2616, 0x0106**): /* PS Audio NuWave DAC */

**Comment by sonorejr** [comment]
I checked the DirectStream and the DirectStream JR and they are can't work as configured by PS Audio.

**Comment by norrest** [comment]
can u tell me USB_ID?
lsubs command

**Comment by sonorejr** [comment]
2616:0110 It doesn't work. Also that DAC will convert native DSD back to DoP as part of it's internal process. Your better off just leaving in DoP format so the DAC doesn't have to do the extra work.

**Comment by norrest** [comment]
> Convert native DSD back to DoP as part of it's internal process
Do you have proofs? 
Thank you!!!!!!

**Comment by sonorejr** [comment]
I asked Ted S. about it via e-mail.

**Comment by norrest** [comment]
Ok, if he answer, please write!

**Comment by norrest** [comment]
Hi @sonorejr !
Do you have any news?
