### ISSUE TITLE
TEAC-501

### ISSUE THREAD

**Issue by storrgie** [lintweaker/xmos-native-dsd#19]
I have a TEAC-UD501 and am willing to do some testing. I looked for the 'archived' issue but couldn't find it.

**Comment by lintweaker** [comment]
All tests with the normal needed modifications have been done to no avail. Maybe I can make it work if a had a UD501 in my possession for a while.
The patches are in patches/archive if you like to give it a try.

**Comment by storrgie** [comment]
I'd be willing to ship to you for a duration if you're wanting to hack on it. I can also run the patchset eventually. If interested, feel free to email me and we can work out shipping arrangements.
