### ISSUE TITLE
Global patch create

### ISSUE THREAD

**Issue by norrest** [lintweaker/xmos-native-dsd#34]
Hi! Can you crate global patch for all dsd dacs?

**Comment by norrest** [comment]
**for v4.14 kernel**

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/sound/usb/quirks.c?h=v4.14.13

**Comment by norrest** [comment]
Its Ok?
[patch.txt](https://github.com/lintweaker/xmos-native-dsd/files/1628290/patch.txt)

**Comment by norrest** [comment]
[patch.txt](https://github.com/lintweaker/xmos-native-dsd/files/1628291/patch.txt)
Its ok?

**Comment by lintweaker** [comment]
It is still on my todo (low prio). The items need to be in order, lower id's first. But a good first attempt :-)

**Comment by norrest** [comment]
This patch dont work? (

**Comment by norrest** [comment]
case USB_ID(0x20b1, 0x3086): /Singxer F-1 converter board/
case USB_ID(0x20b1, 0x3086): /ARMATURE Hecate /

**Comment by norrest** [comment]
[dsd_native.txt](https://github.com/lintweaker/xmos-native-dsd/files/1628315/dsd_native.txt) So?

**Comment by norrest** [comment]
So? 
[dsd_native.txt](https://github.com/lintweaker/xmos-native-dsd/files/1628317/dsd_native.txt)

**Comment by lintweaker** [comment]
almost, you also need to order the second number (so first on manufacturer id, then on device id).

**Comment by norrest** [comment]
there are numbers and letters,  how to sort correctly? This is generally important? Or just for beauty! Can you help?
Is there a ready-made file?
