### ISSUE TITLE
Is this patch still necessary with Ubuntu 18 and ALSA 1.1.9?

### ISSUE THREAD

**Issue by Juno808** [lintweaker/xmos-native-dsd#41]
Hi,

Is this patch still necessary with Ubuntu 18.04 and ALSA 1.1.9?

Do we still need to compile Kernel to add native DSD support?

Thank you.

Juno

**Comment by lintweaker** [comment]
Hi,
Not sure which specific patch you are referring to but ALSA has been DSD ready from quite some years and a lot of device specific DSD patches have made it into the kernel

**Comment by Juno808** [comment]
Hi lintweaker,

Thanks for your reply. And thanks for your greats works related to DSD.

I was referring to patches for Kernel. I am using Kernel 5.0.0-25-Generic from Ubuntu 18. Do I need to recompile the Kernel to include ALSA drivers for DSD? Or would it just work?

Thank you.

Juno

**Comment by lintweaker** [comment]
Hi,
I was referring to the kernel patches as well. A lot of them (if not all and more) are in the stock kernel.
