### ISSUE TITLE
update errors

### ISSUE THREAD

**Issue by norrest** [lintweaker/xmos-native-dsd#7]
Hi!
I use kernel from https://www.kernel.org/  	 linux-3.18.25
unpack to directory /usr/temo/linux-3.18.25
but 

/usr/temo/linux-3.18.25# sudo patch -p1 < /usr/temo/git/SRPMS/patches/kernel/alsa-add-dsd-u32-le-v5.patch --dry-run
checking file include/sound/pcm.h
Hunk #1 FAILED at 183.
1 out of 1 hunk FAILED
checking file include/uapi/sound/asound.h
Hunk #1 FAILED at 219.
1 out of 1 hunk FAILED
checking file sound/core/pcm.c
Hunk #1 FAILED at 215.
1 out of 1 hunk FAILED
checking file sound/core/pcm_misc.c
Hunk #1 succeeded at 160 with fuzz 2 (offset 12 lines).

**Comment by lintweaker** [comment]
Hello,
Kernel 3.18.25 already has these patches included.
